application/models/__init__.py
from ._base import db
from .user import *

application/models/_base.py
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

application/models/user.py
# coding: utf-8
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from ._base import db
from ..utils.uploadsets import avatars


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(50), unique=True)
    avatar = db.Column(db.String(200), default='default.png')
    password = db.Column(db.String(200))
    is_admin = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.now)

    def __setattr__(self, name, value):
        # Hash password when set it.
        if name == 'password':
            value = generate_password_hash(value)
        super(User, self).__setattr__(name, value)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def avatar_url(self):
        return avatars.url(self.avatar)

    def __repr__(self):
        return '<User %s>' % self.name

application/forms/__init__.py
from .account import *

application/forms/_helper.py
# coding: utf-8
import re
from urlparse import urlparse


def check_url(form, field):
    """Check url schema."""
    url = field.data.strip()
    if not url:
        return
    result = urlparse(url)
    if result.scheme == "":
        field.data = "http://%s" % re.sub(r'^:?/*', '', url)

application/forms/account.py
# coding: utf-8
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from ..models import User


class SigninForm(Form):
    """Form for signin"""
    email = StringField('Email',
                        validators=[
                            DataRequired("Email shouldn't be empty."),
                            Email('Email format is not correct.')
                        ])

    password = PasswordField('Password',
                             validators=[DataRequired("Password shouldn't be empty.")])

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if not user:
            raise ValueError("Account doesn't exist.")

    def validate_password(self, field):
        if self.email.data:
            user = User.query.filter(User.email == self.email.data).first()
            if not user or not user.check_password(self.password.data):
                raise ValueError('Password is not correct.')
            else:
                self.user = user


class SignupForm(Form):
    """Form for signin"""
    name = StringField('Username',
                       validators=[DataRequired("Username shouldn't be empty.")])

    email = StringField('Email',
                        validators=[
                            DataRequired(message="Email shouldn't be empty."),
                            Email(message='Email format is not correct.')
                        ])

    password = PasswordField('Password',
                             validators=[DataRequired("Password shouldn't be empty.")])

    repassword = PasswordField('Retype password',
                               validators=[
                                   DataRequired("Please retype the password."),
                                   EqualTo('password', message="Passwords must match.")
                               ])

    def validate_name(self, field):
        user = User.query.filter(User.name == self.name.data).first()
        if user:
            raise ValueError('This username already exists.')

    def validate_email(self, field):
        user = User.query.filter(User.email == self.email.data).first()
        if user:
            raise ValueError('This email already exists.')

application/__init__.py
# coding: utf-8
import sys
import os

# Insert project root path to sys.path
project_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_path not in sys.path:
    sys.path.insert(0, project_path)

import time
import logging
from flask import Flask, request, url_for, g, render_template
from flask_wtf.csrf import CsrfProtect
from flask.ext.uploads import configure_uploads
from flask_debugtoolbar import DebugToolbarExtension
from werkzeug.wsgi import SharedDataMiddleware
from werkzeug.contrib.fixers import ProxyFix
from six import iteritems
from .utils.account import get_current_user
from config import load_config

# convert python's encoding to utf8
try:
    from imp import reload

    reload(sys)
    sys.setdefaultencoding('utf8')
except (AttributeError, NameError):
    pass


def create_app():
    """Create Flask app."""
    config = load_config()

    if config.DEBUG or config.TESTING:
        app = Flask(__name__)
    else:
        app = Flask(__name__, template_folder=os.path.join(project_path, 'output/templates'))

    app.config.from_object(config)

    if not hasattr(app, 'production'):
        app.production = not app.debug and not app.testing

    # Proxy fix
    app.wsgi_app = ProxyFix(app.wsgi_app)

    # CSRF protect
    CsrfProtect(app)

    # Log errors to stderr in production mode
    if app.production:
        app.logger.addHandler(logging.StreamHandler())
        app.logger.setLevel(logging.ERROR)

        # Enable Sentry
        if app.config.get('SENTRY_DSN'):
            from .utils.sentry import sentry

            sentry.init_app(app, dsn=app.config.get('SENTRY_DSN'))

        # Serve static files during production
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/': os.path.join(project_path, 'output')
        })
    else:
        DebugToolbarExtension(app)

        # Serve static files during development
        app.wsgi_app = SharedDataMiddleware(app.wsgi_app, {
            '/uploads': os.path.join(app.config.get('PROJECT_PATH'), 'uploads')
        })

    # Register components
    register_db(app)
    register_routes(app)
    register_jinja(app)
    register_error_handle(app)
    register_uploadsets(app)
    register_hooks(app)

    return app


def register_jinja(app):
    """Register jinja filters, vars, functions."""
    from .utils import filters, permissions, helpers

    app.jinja_env.filters.update({
        'timesince': filters.timesince
    })

    def url_for_other_page(page):
        """Generate url for pagination."""
        view_args = request.view_args.copy()
        args = request.args.copy().to_dict()
        combined_args = dict(view_args.items() + args.items())
        combined_args['page'] = page
        return url_for(request.endpoint, **combined_args)

    rules = {}
    for endpoint, _rules in iteritems(app.url_map._rules_by_endpoint):
        if any(item in endpoint for item in ['_debug_toolbar', 'debugtoolbar', 'static']):
            continue
        rules[endpoint] = [{'rule': rule.rule} for rule in _rules]

    app.jinja_env.globals.update({
        'absolute_url_for': helpers.absolute_url_for,
        'url_for_other_page': url_for_other_page,
        'rules': rules,
        'permissions': permissions
    })


def register_db(app):
    """Register models."""
    from .models import db

    db.init_app(app)


def register_routes(app):
    """Register routes."""
    from . import controllers
    from flask.blueprints import Blueprint

    for module in _import_submodules_from_package(controllers):
        bp = getattr(module, 'bp')
        if bp and isinstance(bp, Blueprint):
            app.register_blueprint(bp)


def register_error_handle(app):
    """Register HTTP error pages."""

    @app.errorhandler(403)
    def page_403(error):
        return render_template('site/403.html'), 403

    @app.errorhandler(404)
    def page_404(error):
        return render_template('site/404.html'), 404

    @app.errorhandler(500)
    def page_500(error):
        return render_template('site/500.html'), 500


def register_uploadsets(app):
    """Register UploadSets."""
    from .utils.uploadsets import avatars

    configure_uploads(app, (avatars))


def register_hooks(app):
    """Register hooks."""

    @app.before_request
    def before_request():
        g.user = get_current_user()
        if g.user and g.user.is_admin:
            g._before_request_time = time.time()

    @app.after_request
    def after_request(response):
        if hasattr(g, '_before_request_time'):
            delta = time.time() - g._before_request_time
            response.headers['X-Render-Time'] = delta * 1000
        return response


def _get_template_name(template_reference):
    """Get current template name."""
    return template_reference._TemplateReference__context.name


def _import_submodules_from_package(package):
    import pkgutil

    modules = []
    for importer, modname, ispkg in pkgutil.iter_modules(package.__path__,
                                                         prefix=package.__name__ + "."):
        modules.append(__import__(modname, fromlist="dummy"))
    return modules

application/controllers/account.py
# coding: utf-8
from flask import render_template, Blueprint, redirect, request, url_for
from ..forms import SigninForm, SignupForm
from ..utils.account import signin_user, signout_user
from ..utils.permissions import VisitorPermission, UserPermission
from ..models import db, User

bp = Blueprint('account', __name__)


@bp.route('/signin', methods=['GET', 'POST'])
@VisitorPermission()
def signin():
    """Signin"""
    form = SigninForm()
    if form.validate_on_submit():
        signin_user(form.user)
        return redirect(url_for('site.index'))
    return render_template('account/signin.html', form=form)


@bp.route('/signup', methods=['GET', 'POST'])
@VisitorPermission()
def signup():
    """Signup"""
    form = SignupForm()
    if form.validate_on_submit():
        params = form.data.copy()
        params.pop('repassword')
        user = User(**params)
        db.session.add(user)
        db.session.commit()
        signin_user(user)
        return redirect(url_for('site.index'))
    return render_template('account/signup.html', form=form)


@bp.route('/signout')
def signout():
    """Signout"""
    signout_user()
    return redirect(request.referrer or url_for('site.index'))

application/controllers/site.py
# coding: utf-8
from flask import render_template, Blueprint

bp = Blueprint('site', __name__)


@bp.route('/')
def index():
    """Index page."""
    return render_template('site/index.html')


@bp.route('/about')
def about():
    """About page."""
    return render_template('site/about.html')

application/templates/layout.html
<!doctype html>
<html>
<head>
    <title>{% block page_title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    {% block meta %}{% endblock %}
    <link rel="Shortcut Icon" href="/static/image/favicon.png">
    {# CSS libs #}
    <link rel="stylesheet" href="/static/css/libs/bootstrap.min.css"/>
    <link rel="stylesheet" href="/static/css/libs/font-awesome.min.css"/>
    {# CSS layout #}
    <link rel="stylesheet" href="/static/css/bootstrap.theme.css"/>
    <link rel="stylesheet" href="/static/css/common.css"/>
    <link rel="stylesheet" href="/static/css/macros/_user.css"/>
    <link rel="stylesheet" href="/static/css/layout.css"/>
    {# CSS page #}
    {% block page_css %}{% endblock %}
    {# JS global vars #}
    <script type="text/javascript">
        var g = {
            domain: "{{ config.SITE_DOMAIN }}",
            csrfToken: "{{ csrf_token() }}",
            rules: {{ rules|safe }},
            method: "{{ request.method }}",
            signin: {% if g.user %}true{% else %}false{% endif %},
            userId: {% if g.user %}{{ g.user.id }}{% else %}false{% endif %}
        };
    </script>
    {# JS libs #}
    <script src="/static/js/libs/respond.min.js"></script>
    <script src="/static/js/libs/jquery.min.js"></script>
    <script src="/static/js/libs/bootstrap.min.js"></script>
    <script src="/static/js/init.js"></script>
</head>

<body>

{# Flash message #}
{% with message = get_flashed_messages()[0] %}
    {% if message %}
        <div class="alert alert-info flash-message">{{ message }}</div>
    {% endif %}
{% endwith %}

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('site.index') }}">
                Wochang
            </a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li id="nav-index">
                    <a href="{{ url_for('site.index') }}">Home</a>
                </li>
                <li id="nav-about">
                    <a href="{{ url_for('site.about') }}">About</a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="input-group">
                    <input type="text" name="keyword" class="form-control input-sm"
                           placeholder="">
               <span class="input-group-btn">
                  <button class="btn btn-default btn-sm" type="submit">
                      <span class="fa fa-search"></span>
                  </button>
               </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                {% if g.user %}
                    <li id="nav-settings">
                        <a href="#">{{ g.user.name }}</a>
                    </li>
                    <li>
                        <a href="{{ url_for('account.signout') }}">Sign out</a>
                    </li>
                {% else %}
                    <li id="nav-signin">
                        <a href="{{ url_for('account.signin') }}">Sign in</a>
                    </li>
                    <li id="nav-signup">
                        <a href="{{ url_for('account.signup') }}">Sign up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div id="main-wap">
    {% block page_content %}{% endblock %}
</div>

<div id="footer">
    <div class='container'>
        <div id='copyright' class="pull-left">
            © 2015 Wochang
        </div>

        <ul id='links' class="pull-right list-unstyled list-inline">
            <li><a href="{{ url_for('site.about') }}">About</a></li>
        </ul>
    </div>
</div>

{# JS layout #}
<script src="/static/js/layout.js"></script>

{# JS page #}
{% block page_js %}{% endblock %}

</body>
</html>